- README.md
Can you check that, @paulirish?
> Improve puppeteer copy

- README.md
- packages/browserless/src/index.js
- packages/goto/package.json
- packages/goto/scripts/postinstall.js
- packages/goto/src/index.js
- packages/goto/src/is-tracker.js
> feat: add builtin adblock

- packages/goto/package.json
- packages/goto/scripts/postinstall.js
- packages/goto/src/index.js
**Checklist**
**Description**
This PR is an effort to use good lists by default, removing some duplicate list of selector already included into other lists.
Closes #50
> build: improve default ads lists

- README.md
- packages/examples/src/screenshot.js
- packages/screenshot/package.json
- packages/screenshot/src/index.js
> feat: add bg url overlay

- packages/screenshot/src/index.js
related: https://github.com/GoogleChrome/puppeteer/issues/2692#issuecomment-414319342
> build: ensure fonts are loaded

- packages/browserless/src/index.js
related with https://github.com/GoogleChrome/puppeteer/issues/4428\#issuecomment-500184469
> feat: respawn the browser under be closed unexpectedly

- .travis.yml
- packages/browserless/package.json
- packages/browserless/src/index.js
- packages/goto/package.json
avoid zombie process, it's based on https://github.com/GoogleChrome/puppeteer/issues/1825
> kill & respawn a new browser instance under diconnect

- packages/screenshot/src/prepare.js
**Test URL**
- https://output.jsbin.com/sutacedare
- https://with-google-analytics-app-p6i63vwuu.now.sh/
> feat: close alert before taking a screenshot

- README.md
- packages/browserless/src/index.js
- packages/devices/src/devices.json
- packages/examples/src/pdf.js
- packages/goto/src/index.js
- packages/pdf/src/index.js
- packages/screenshot/src/prepare.js
> feat: extends devices & setup better defaults

- packages/goto/src/index.js
Closes #126
Closes #127
Closes #129
> feat: Rename some API parameters

- packages/goto/src/index.js
The browser actions can be grouped into two things
- actions that need to be run _before_ goto operation
- actions that need to be run _after_ goto operation
Although they don't consume too much time, instead of setup them on series, I grouped them into an array of promise to wait until go to the next step.
Also, added a simple way to log every action or error (if it happens) in a way you don't need to declare it across the code.
> perf: browser actions on parallel

- packages/devices/src/devices.json
- packages/devices/src/index.js
BREAKING CHANGE: It needs puppeteer 3.x
closes #164
> feat: use object map interface

- packages/browserless/package.json
- packages/browserless/src/index.js
> build: remove lazy import

- README.md
- package.json
- packages/browserless/src/index.js
- packages/cli/package.json
- packages/devices/package.json
- packages/devices/src/index.js
- packages/goto/package.json
- packages/goto/src/index.js
> build: add timezone emulation

- README.md
- packages/browserless/package.json
- packages/browserless/src/driver.js
- packages/browserless/src/index.js
> feat: add proxy support

- packages/goto/src/index.js
- packages/screenshot/src/index.js
related to https://github.com/puppeteer/puppeteer/issues/1353#issuecomment-723164059
> fix: close dialog before take the screenshot

- packages/browserless/src/driver.js
- packages/browserless/src/index.js
I noted parent is PID is not always present
> refactor: destroy pids consistently

- README.md
It is nothing big, just some typos.
> Fix minor spelling mistakes in the main README.

- packages/browserless/src/driver.js
- packages/browserless/src/index.js
- Rename `.getPids` into `.getChildrenPids`.
- First close if method is available, fallbacking into `process.kill`.
- Added `getBrowserContext` internal method.
- Better debug traces for `createPage`/`closePage`/`destroyContext`
> fix(driver): improve kill management

- packages/goto/src/index.js
this is specially oriented for data URI images
> fix(goto): truncate excessive long URLs

- CHANGELOG.md
- README.md
- package.json
- packages/benchmark/src/index.js
- packages/benchmark/src/timing.js
- packages/browserless/test/index.js
- packages/cli/src/index.js
- packages/goto/test/e2e/evasions.js
- packages/goto/test/index.js
- packages/goto/test/unit/evasions/index.js
- packages/goto/test/unit/headers/index.js
- packages/screenshot/test/pretty.js
- packages/test/index.js
- packages/test/util.js
just to reflect the same nomenclature as the documentation
> refactor: internal variable

- packages/goto/src/index.js
It makes easier debug for a specific domain logs
> refactor: scoped logs

- packages/browserless/src/index.js
> fix: silently capture close error

- README.md
Ref: https://github.com/microlinkhq/browserless/issues/596
> fix(docs): await createContext

- packages/browserless/test/index.js
- packages/test/util/create.js
Discussed at https://github.com/puppeteer/puppeteer/issues/13599
> test: fix proxyUrl

- packages/goto/src/index.js
This is a temporary workaround since disabling the ad blocker also disables request interception, so a function is necessary to check whether interception is enabled or not to avoid undesirable scenarios.
> chore(goto): add isRequestInterceptionEnabled helper
